### ISSUE TITLE
How to run chime on google colab?

### ISSUE THREAD

**Issue by hafidh561** [MaxHalford/chime#22]

**Comment by MaxHalford** [comment]
No idea! I suppose you tried and it didn't work? I'll add a todo to take a look, but not sure it's possible because it's a remote computer.

**Comment by hafidh561** [comment]
I've tried it, if I haven't tried it, then I won't ask lol. Maybe in the future, you won't make it work on colab.

**Comment by MaxHalford** [comment]
> I've tried it, if I haven't tried it, then I won't ask lol.

I ask because you didn't really expand. Did you get an error message? A traceback maybe?

> Maybe in the future, you won't make it work on colab.

Sorry, I don't understand this sentence. Can you clarify?

**Comment by hafidh561** [comment]
> I ask because you didn't really expand. Did you get an error message? A traceback maybe? 

No, just don't do anything. The sound not running. The cell runs normally.
> Sorry, I don't understand this sentence. Can you clarify?   

I can't run chime on google colab, maybe you want to fix this issue in the future.

**Comment by MaxHalford** [comment]
Ok I'm not sure how to solve this the clean way, and I don't have a lot of time to investigate.

However, here's a hacky workaround:

```py
import chime
import IPython

IPython.display.Audio(str(chime.themes_dir() / "zelda" / "success.wav"), autoplay=True)
```
