### ISSUE TITLE
Add a `chime` command for cli usage

### ISSUE THREAD

**Issue by paw-lu** [MaxHalford/chime#5]
Cool library!

Would be great if we named the command so you could call the script from the command line using

```sh
% chime
```

instead of having to use

```sh
% python -m chime
```

This would also allow users to install the library using installers like [pipx](https://github.com/pipxproject/pipx) if they were interested in using it as a command-line tool.

**Comment by paw-lu** [comment]
#6 attempts to implement this.

**Comment by MaxHalford** [comment]
The PR's quality was really good, thanks a ton.

**Comment by MaxHalford** [comment]
@paw-lu the CI tests are failing, probably because poetry isn't used to install chime. Do you want to take a look?

**Comment by MaxHalford** [comment]
I added status check enforcement in pull requests so that this doesn't happen again :)

**Comment by paw-lu** [comment]
> @paw-lu the CI tests are failing, probably because poetry isn't used to install chime. Do you want to take a look?

Did not notice the CI tests 😅, thanks for the heads up! Like you alluded, the test fails because the package is never installed in the CI.

It should be (hopefully) easy to fix. I'll split this up into two PRs:

1. Update `pyproject.toml` and `poetry.lock` [to support Poetry >=1.1.0](https://python-poetry.org/blog/announcing-poetry-1-1-0.html) (so it will work with a fresh install of poetry in the CI)
2. Change `.github/workflows/tests.yml` to use Poetry to install the package before running pytest

**Comment by MaxHalford** [comment]
Ok cool! Once you're done I'll release a new version on PyPI :)

**Comment by paw-lu** [comment]
> 1. Update pyproject.toml and poetry.lock to support Poetry >=1.1.0 (so it will work with a fresh install of poetry in the CI)

#8 addresses the first part of this change.

**Comment by MaxHalford** [comment]
Tests are fixed, good job @paw-lu :)
